tweets/urls.py
from django.conf.urls import url
from tweets.views import ListTweets, AddTweet, ShowTweet, EditTweet, DeleteTweet, TimeLine, CreateFavorite, DeleteFavorite, CreateRT, DeleteRT, ListFavorites, ListRetweets

urlpatterns = [
    url(r'^$', ListTweets.as_view(), name='tweets_home'),
    url(r'^add_tweet/$', AddTweet.as_view(), name='add_tweet'),
    url(r'^tweet/(?P<id_tweet>\d{1,})/$', ShowTweet.as_view(), name='tweet_message'),
    url(r'^delete/(?P<id_tweet>\d{1,})/$', DeleteTweet.as_view(), name='delete_tweet'),
    url(r'^edit_tweet/(?P<id_tweet>\d{1,})/$', EditTweet.as_view(), name='edit_tweet'),
    url(r'^timeline/$', TimeLine.as_view(), name='timeline'),

    url(r'^favorite/(?P<id_tweet>\d{1,})/$', CreateFavorite.as_view(), name='favorite'),
    url(r'^favorite/delete/(?P<id_tweet>\d{1,})/$', DeleteFavorite.as_view(), name='del_fav'),

    url(r'^retweet/(?P<id_tweet>\d{1,})/$', CreateRT.as_view(), name='add_rt'),
    url(r'^retweet/delete/(?P<id_tweet>\d{1,})/$', DeleteRT.as_view(), name='del_rt'),

    url(r'^list_favorites/(?P<id_tweet>\d{1,})/$', ListFavorites.as_view(), name='list_favorites'),
    url(r'^list_retweets/(?P<id_tweet>\d{1,})/$', ListRetweets.as_view(), name='list_retweets'),


]

twitter/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
# from tweets.views import new_tweet,show_tweet, delete_tweet, edit_tweet
from tweets.views import tweet_login, tweet_logout
from users.views import Profile
from tweets import urls as tweets_url
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tweet/', include(tweets_url, namespace='tweets_url')),
    url(r'^tweet/login/$', tweet_login, name='tweet_login'),
    url(r'^tweet/logout/$', tweet_logout, name='tweet_logout'),
    url(r'^tweet/update_profile/(?P<pk>\d{1,})/$', Profile.as_view(), name='update_profile'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

tweets/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tweet(models.Model):
    tweet = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    user_favs = models.ManyToManyField(User, through='tweets.Favorite', related_name='user_favs')
    user_rts = models.ManyToManyField(User, through='tweets.ReTweet', related_name='user_rts')

    def __unicode__(self):
        return "{0} - {1}".format(self.user, self.date)

class Favorite(models.Model):
    user = models.ForeignKey(User)
    tweet = models.ForeignKey('tweets.Tweet')
    date = models.DateTimeField(auto_now_add=True)


class ReTweet(models.Model):
    user = models.ForeignKey(User)
    tweet = models.ForeignKey('tweets.Tweet')
    date = models.DateTimeField(auto_now_add=True)

tweets/forms.py
from django import forms
from tweets.models import Tweet, Favorite

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['tweet']
        widgets = {
            "tweet" : forms.TextInput(attrs={"class" : "form-control"}),
        }


class FavoriteForm(forms.ModelForm):
    class Meta:
        model = Favorite
        exclude = ['date','user', 'tweet']

tweets/views.py
from django.shortcuts import render,redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from tweets.forms import TweetForm
from tweets.models import Tweet, Favorite, ReTweet
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models import Q


# def new_tweet(request):
#     #return HttpResponse('hola', content_type='text/plain')
#     if request.method == 'POST':
#         form  = TweetForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponse('guardado')
#         else:
#             return render(request, 'tweets/create_tweet.html',{'tweet_form': form})
#
#     form = TweetForm()
#     return render(request, 'tweets/create_tweet.html',{'tweet_form': form})
#

class AddTweet(CreateView):
    template_name = 'tweets/create_tweet.html'
    model = Tweet
    form_class = TweetForm
    success_url = reverse_lazy('tweets_url:tweets_home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddTweet, self).form_valid(form)

# def show_tweet(request, id_tweet):
#
#     # try:
#     #     tweet = Tweet.objects.get(id=id_tweet)
#     # except Tweet.DoesNotExist:
#     #     raise Http404('Ese tweet no existe')
#     tweet  = get_object_or_404(Tweet, id=id_tweet)
#     return render(request, 'tweets/show_tweet.html',{'tweet': tweet})

class ShowTweet(ListView):
    template_name = 'tweets/show_tweet.html'
    context_object_name = 'tweet'
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(id=self.kwargs['id_tweet']).first()
        return super(ShowTweet, self).dispatch(request, *args, **kwargs)


def tweet_login(request):
    template_response = 'tweets/login.html'
    if request.method=='POST':
        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('tweets_url:tweets_home'))
        else:
            messages.error(request, u'Usuario/Password incorrecto')
            return render(request, template_response, {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, template_response, {'form': form})

def tweet_logout(request):
    logout(request)
    return redirect(reverse('tweets_url:tweets_home'))

# def list_tweets(request):
#     # list_tweets = Tweet.objects.all()
#     list_tweets = get_list_or_404(Tweet)
#     return render(request, 'tweets/list_tweets.html',{'list_tweets': list_tweets})

class ListTweets(ListView):
    template_name = 'tweets/list_tweets.html'
    context_object_name = 'list_tweets'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(~Q(user=request.user)).order_by('-date')
        return super(ListTweets, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ListTweets, self).get_context_data(**kwargs)
        context['user_favs'] = Favorite.objects.filter(user=self.request.user).values_list('tweet__id', flat=True)
        context['user_rts'] = ReTweet.objects.filter(user=self.request.user).values_list('tweet__id', flat=True)
        return context



# def delete_tweet(request, id_tweet):
#     Tweet.objects.filter(id=id_tweet).delete()
#     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class DeleteTweet(DeleteView):
    model = Tweet
    form_class = TweetForm
    success_url = reverse_lazy('tweets_url:timeline')
    slug_field = 'id'
    slug_url_kwarg = 'id_tweet'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(id=self.kwargs['id_tweet'])
        request.method = 'POST'
        return super(DeleteTweet, self).dispatch(request, *args, **kwargs)

# def edit_tweet(request, id_tweet):
#     tweet  = get_object_or_404(Tweet, id=id_tweet)
#
#     if request.method == 'POST':
#         form  = TweetForm(request.POST, instance=tweet)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponse('guardado')
#         else:
#             return render(request, 'tweets/update_tweet.html',{'tweet_form': form})
#
#     form = TweetForm(instance=tweet)
#     return render(request, 'tweets/update_tweet.html',{'tweet_form': form})

class EditTweet(UpdateView):
    template_name = 'tweets/update_tweet.html'
    form_class = TweetForm
    success_url = reverse_lazy('tweets_url:timeline')
    slug_field = 'id'
    slug_url_kwarg = 'id_tweet'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(id=self.kwargs['id_tweet'])
        return super(EditTweet, self).dispatch(request, *args, **kwargs)

class TimeLine(ListView):
    template_name = 'tweets/timeline.html'
    context_object_name = 'list_tweets'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(Q(user=request.user)).order_by('-date')
        return super(TimeLine, self).dispatch(request, *args, **kwargs)


class CreateFavorite(View):
    def get(self, request, id_tweet):
        try:
            tweet = get_object_or_404(Tweet, ~Q(user=request.user), id=id_tweet)
            favorite, create = Favorite.objects.get_or_create(user=request.user, tweet=tweet)
        except:
            messages.warning(request, 'No puedes favoritear el tuit')
            return redirect(reverse('tweets_url:tweets_home'))

        messages.success(request, 'Marcado como favorito')
        return redirect(reverse('tweets_url:tweets_home'))

class DeleteFavorite(View):
    def get(self, request, id_tweet):
        try:
            tweet = get_object_or_404(Tweet, ~Q(user=request.user), id=id_tweet)
            get_object_or_404(Favorite, user=request.user, tweet=tweet).delete()
        except:
            messages.warning(request, 'No se puede eliminar favorito')
            return redirect(reverse('tweets_url:tweets_home'))

        messages.success(request, 'Favorito borrado')
        return redirect(reverse('tweets_url:tweets_home'))


class CreateRT(View):
    def get(self, request, id_tweet):
        try:
            tweet = get_object_or_404(Tweet, ~Q(user=request.user), id=id_tweet)
            rt, create = ReTweet.objects.get_or_create(user=request.user, tweet=tweet)
        except:
            messages.warning(request, 'No se puede retuitear')
            return redirect(reverse('tweets_url:tweets_home'))

        messages.success(request, 'RT!')
        return redirect(reverse('tweets_url:tweets_home'))

class DeleteRT(View):
    def get(self, request, id_tweet):
        try:
            tweet = get_object_or_404(Tweet, ~Q(user=request.user), id=id_tweet)
            get_object_or_404(ReTweet, user=request.user, tweet=tweet)
        except:
            messages.warning(request, 'No se puede eliminar el RT')
            return redirect(reverse('tweets_url:tweets_home'))

        messages.success(request, 'RT Eliminado')
        return redirect(reverse('tweets_url:tweets_home'))


class ListFavorites(ListView):
    template_name = 'tweets/list_favorites.html'
    context_object_name = 'favorites'
    slug_field = 'id'
    slug_url_kwarg = 'id_tweet'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(Q(id=self.kwargs['id_tweet'])).first()
        return super(ListFavorites, self).dispatch(request, *args, **kwargs)

class ListRetweets(ListView):
    template_name = 'tweets/list_retweets.html'
    context_object_name = 'favorites'
    slug_field = 'id'
    slug_url_kwarg = 'id_tweet'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.queryset = Tweet.objects.filter(Q(id=self.kwargs['id_tweet'])).first()
        return super(ListRetweets, self).dispatch(request, *args, **kwargs)

templates/tweets/create_tweet.html
{% extends 'bases/base.html' %}
{% block content %}
<div class="col-lg-5">
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-primary">
	</form>
</div>
{% endblock %}

templates/tweets/favorite_form.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

templates/tweets/list_favorites.html
{% extends 'bases/base.html' %}
{% block content %}

<div class="row">

</div>
<div class="row">
  <div class="col-lg-4">
  <div class="col-lg-8">
    <p>{{ favorites.tweet }}</p>
    <ul class="list-group">
      {% if favorites.user_favs.all %}
        {% for user in favorites.user_favs.all %}
          <li class="list-group-item">{{ user.username }}<small></small></li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
  </div>
</div>
{% endblock %}

templates/tweets/list_retweets.html
{% extends 'bases/base.html' %}
{% block content %}

<div class="row">

</div>
<div class="row">
  <div class="col-lg-4">
  <div class="col-lg-8">
    <p>{{ favorites.tweet }}</p>
    <ul class="list-group">
      {% if favorites.user_rts.all %}
        {% for user in favorites.user_rts.all %}
          <li class="list-group-item">{{ user.username }}<small></small></li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
  </div>
</div>
{% endblock %}

templates/tweets/list_tweets.html
{% extends 'bases/base.html' %}
{% block content %}

<div class="row">

</div>
<div class="row">
  <div class="col-lg-4">
    <p>Username: {{ request.user.username }}</p>
    <p>Name: {{ request.user.first_name }} {{ request.user.last_name }}</p>
    <p>Email: {{ request.user.email }}</p>
    <p><a href="{% url 'update_profile' pk=request.user.id %}">Edit profiile</a><p>
    <p><a href="{% url 'tweets_url:timeline' %}">Timeline</a><p>
  </div>
  <div class="col-lg-8">
    <form method="post" action="{% url 'tweets_url:add_tweet'%}">
      {% csrf_token %}
      <textarea name="tweet" id="tweet" rows="3" class="form-control"></textarea>
      <input type="submit" name="submit" class="btn btn-primary" value="Tweet">
    </form>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}



    <ul class="list-group">
        {% for tweets in list_tweets %}
            <li class="list-group-item">
              <label for="">@{{ tweets.user }}:</label>
              <p>
                {{ tweets.tweet }}
              </p>
              <label for=""><small>{{ tweets.date }}</small></label>
              <a href="{% url 'tweets_url:list_favorites' id_tweet=tweets.id %}">{{ tweets.user_favs.count }}</a>
              {% if tweets.id in user_favs %}
                <small><a href="{% url 'tweets_url:del_fav' id_tweet=tweets.id  %}">Delete favorite</a></small>
              {% else %}
                <small><a href="{% url 'tweets_url:favorite' id_tweet=tweets.id  %}">Add favorite</a></small>
              {% endif %}

              <a href="{% url 'tweets_url:list_retweets' id_tweet=tweets.id %}">{{ tweets.user_rts.count }}</a>
              {% if tweets.id in user_rts %}
                <small><a href="{% url 'tweets_url:del_rt' id_tweet=tweets.id  %}">Delete Retweet</a></small>
              {% else %}
                <small><a href="{% url 'tweets_url:add_rt' id_tweet=tweets.id  %}">Retweet</a></small>
              {% endif %}


            </li>
        {% endfor %}
    </ul>
  </div>
</div>



  <a href="{% url 'tweet_logout' %}">logout</a>
  <a href="{% url 'tweets_url:add_tweet' %}">add tweet</a>
{% endblock %}

templates/tweets/login.html
{% extends 'bases/base.html' %}
  {% block content %}
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}  
    <form method="POST">
      {% csrf_token %}
    {{ form }}
    <input type="submit" value="login">
    </form>
{% endblock %}

templates/tweets/show_tweet.html
{% extends 'bases/base.html' %}
{% block content %}
  {% if tweet.tweet %}
    <h1>{{ tweet.tweet }}</h1>
  {% else %}
  {% endif %}
{% endblock %}

templates/tweets/timeline.html
{% extends 'bases/base.html' %}
{% block content %}

<div class="row">

</div>
<div class="row">
  <div class="col-lg-4">
    <p><a href="{% url 'tweets_url:tweets_home' %}">Home</a></p>
    <p>Username: {{ request.user.username }}</p>
    <p>Name: {{ request.user.first_name }} {{ request.user.last_name }}</p>
    <p><a href="{% url 'update_profile' request.user.id %}">Edit profiile</a><p>
  </div>
  <div class="col-lg-8">
    <form method="post" action="{% url 'tweets_url:add_tweet'%}">
      {% csrf_token %}
      <textarea name="tweet" id="tweet" rows="3" class="form-control"></textarea>
      <input type="submit" name="submit" class="btn btn-primary" value="Tweet">
    </form>
    <ul class="list-group">
        {% for tweets in list_tweets %}
            <li class="list-group-item">
              <label for="">Nombre: {{ tweets.name }}</label>
              <p>
                {{ tweets.tweet }}
              </p>
              <label for=""><small>{{ tweets.date }}</small></label>
              <a href="{% url 'tweets_url:tweet_message' id_tweet=tweets.id %}" class="href">more</a>
              <a href="{% url 'tweets_url:delete_tweet' id_tweet=tweets.id %}">delete</a>
              <a href="{% url 'tweets_url:edit_tweet' id_tweet=tweets.id %}">edit</a>

            </li>
        {% endfor %}
    </ul>
  </div>
</div>



  <a href="{% url 'tweet_logout' %}">logout</a>
  <a href="{% url 'tweets_url:add_tweet' %}">add tweet</a>
{% endblock %}

templates/tweets/update_tweet.html
{% extends 'bases/base.html' %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>
{% endblock %}